messages:
  invalid-cmd: "&8&lMMOCore&r &6&lBoosters &7&l> &ainvalid command arguments!"
  reload: "&8&lMMOCore&r &6&lBoosters &7&l> &asuccessfully reloaded!"
  debug: "&8&lMMOCore&r &6&lBoosters &7&l> &adebug toggled!"
  perm-add: "&8&lMMOCore&r &6&lBoosters &7&l> &asuccessfully added booster!"
  boost-add: "&8&lMMOCore&r &6&lBoosters &7&l> &asuccessfully given a booster!"
  boost-use: "&8&lMMOCore&r &6&lBoosters &7&l> &asuccessfully used a booster!"
  boost-expire: "&8&lMMOCore&r &6&lBoosters &7&l> &abooster has expired!"
  boost-list-header: "&6------------&8&lMMOCore&r &6&lBoosters&8------------"
  boost-list: "&8&lMMOCore&r &6&lBoosters &7&l> &a%type% for %timeleft%m at x%percent%!"
  invalid-boost: "&8&lMMOCore&r &6&lBoosters &7&l> &cPlayer does not have that booster!"
debug: true
mmocoreb:
-  "&7----------&8&lMMOCore&r &6&lBoosters&7----------"
-  "&e&l/mmocoreb reload &7&l> &freloads the plugin!"
-  "&e&l/mmocoreb give <player> <class/profess> <x> <time> &7&l> &fgives players a timed booster!"
-  "&e&l/mmocoreb give <player> <class/profess> <x> &7&l> &fgives players a permanent booster!"
booster:
  mat: "emerald"
  name: "&8&lMMOCore&r &6&lBooster"
  glow: true
  lore:
  - " "
  -  "&6&lProfess/Class"
  -  "&8&l[%type%]"
  -  " "
  -  "&6&lTime"
  -  "&8&l[%time%m]"
  - " "
  -  "&6&lMultiplier"
  -  "&8&l[x%percent%]"